export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
    GET_ALL_USER_REQUEST: "GET_ALL_USER_REQUEST",
    GET_ALL_USER_FAILURE: "GET_ALL_USER_FAILURE",
    GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",

    UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",

    DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
    DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
};


export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
    UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
    UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
    UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
    DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
    DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
    DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};

export const brandConstants = {
    GET_ALL_BRANDS_REQUEST: "GET_ALL_BRANDS_REQUEST",
    GET_ALL_BRANDS_SUCCESS: "GET_ALL_BRANDS_SUCCESS",
    GET_ALL_BRANDS_FAILURE: "GET_ALL_BRANDS_FAILURE",
    ADD_NEW_BRAND_REQUEST: "ADD_NEW_BRAND_REQUEST",
    ADD_NEW_BRAND_SUCCESS: "ADD_NEW_BRAND_SUCCESS",
    ADD_NEW_BRAND_FAILURE: "ADD_NEW_BRAND_FAILURE",
    UPDATE_BRANDS_REQUEST: "UPDATE_BRANDS_REQUEST",
    UPDATE_BRANDS_SUCCESS: "UPDATE_BRANDS_SUCCESS",
    UPDATE_BRANDS_FAILURE: "UPDATE_BRANDS_FAILURE",
    DELETE_BRANDS_REQUEST: "DELETE_BRANDS_REQUEST",
    DELETE_BRANDS_SUCCESS: "DELETE_BRANDS_SUCCESS",
    DELETE_BRANDS_FAILURE: "DELETE_BRANDS_FAILURE",
};

export const initDataConstants = {
    GET_ALL_INIT_DATA_REQUEST: "GET_ALL_INIT_DATA_REQUEST",
    GET_ALL_INIT_DATA_SUCCESS: "GET_ALL_INIT_DATA_SUCCESS",
    GET_ALL_INIT_DATA_FAILURE: "GET_ALL_INIT_DATA_FAILURE",
};

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

    GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
    GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
    GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",

    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

    UPDATE_DISCOUNT_REQUEST: "UPDATE_DISCOUNT_REQUEST",
    UPDATE_DISCOUNT_SUCCESS: "UPDATE_DISCOUNT_SUCCESS",
    UPDATE_DISCOUNT_FAILURE: "UPDATE_DISCOUNT_FAILURE",
}

export const orderConstants = {
    GET_ALL_ORDERS_REQUEST: "GET_ALL_ORDERS_REQUEST",
    GET_ALL_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS",
    GET_ALL_ORDERS_FAILURE: "GET_ALL_ORDERS_FAILURE",

    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};

export const sizeConstants = {
    GET_ALL_SIZE_REQUEST: "GET_ALL_SIZE_REQUEST",
    GET_ALL_SIZE_SUCCESS: "GET_ALL_SIZE_SUCCESS",
    GET_ALL_SIZE_FAILURE: "GET_ALL_SIZE_FAILURE",

    ADD_SIZE_REQUEST: "ADD_SIZE_REQUEST",
    ADD_SIZE_SUCCESS: "ADD_SIZE_SUCCESS",
    ADD_SIZE_FAILURE: "ADD_SIZE_FAILURE",

    UPDATE_SIZE_REQUEST: "UPDATE_SIZE_REQUEST",
    UPDATE_SIZE_SUCCESS: "UPDATE_SIZE_SUCCESS",
    UPDATE_SIZE_FAILURE: "UPDATE_SIZE_FAILURE"
}

export const API_URL = "https://api-sportswear.herokuapp.com";